"""
The settings window.

    venv\\Scripts\\python.exe settings_ui.py        (standalone, for development)

Reached in normal use from the tray: right-click -> Settings.

**A non-coder must never be told to edit settings.json.** Until now that file was
the only interface, which asked someone to open a text editor, understand JSON,
know that a trailing comma breaks it, and know what `int8`, `beam_size` and
`vad_filter` mean. The file stays supported for people who prefer it; it stops
being the way settings are changed.

Three rules every control here follows:

  1. Plain language. The user picks "Hindi and English mixed", not
     `whisper_model: swift-ct2`. Nothing in this window says int8 or beam_size.
  2. Say what it costs. A slower choice says so, with the measured number, because
     "why did it get slow" is otherwise unanswerable.
  3. Never silently do nothing. Where a restart is genuinely required, say so.

tkinter is used because it is already a dependency via the overlay fallback, so
this adds nothing to the download.
"""

import json
import logging
import sys
import threading
import webbrowser
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import tkinter as tk
from tkinter import messagebox, ttk

from config import DEFAULTS, LOCAL_SETTINGS_FILE, SETTINGS_FILE, load_config
from paths import DATA_DIR, apply_window_icon

log = logging.getLogger("casper.settings_ui")

# Model tiers, described by what they do rather than what they are called.
#
# Every figure here is a cell in the table in corpus/RESULTS.md, regenerated by
# `bench_hinglish.py` against 30 recordings of a real speaker. Accuracy is
# `1 - fair WER` for the category the profile is chosen for, so the number next to
# "Mostly English" is the english row and the number next to "Hindi and English
# mixed" is the code-switch row. Quoting an aggregate instead would flatter both:
# each model is very bad at the other one's job.
#
# A third profile ("Most accurate", claiming 86% and 19s) used to sit here. It
# named a model, `apex-ct2`, that exists nowhere - not bundled, not a HuggingFace
# id, no conversion script - so choosing it broke transcription until the fallback
# caught it, and its two figures had no measurement behind them. Removed rather
# than re-pointed: an option is not a feature until something answers it.
PROFILES = [
    {
        "id": "swift-ct2",
        "label": "Hindi and English mixed",
        "detail": "Best for Hinglish. 81% accurate on mixed speech, about 1.3s. "
                  "Included in the download.",
        "language": "en",
    },
    {
        "id": "base.en",
        "label": "Mostly English",
        "detail": "Best for English only. 91% accurate, about 1.1s. Cannot "
                  "transcribe Hindi at all.",
        "language": "en",
    },
]

OVERLAY_STYLES = [
    ("blob", "Blob", "A soft shape that pulses with your voice. No text."),
    ("caption", "Live captions", "Shows words as you speak. Downloads a small "
                                 "extra model the first time."),
    ("capsule", "Compact bar", "A small bar with a level meter and a timer."),
]

# Layout modes. Ordered plain first, because that is the default and the only one
# that cannot change what you meant.
FORMAT_MODES = [
    ("plain", "Plain text",
     "Just tidy it up. Nothing is reworded or laid out. This is the default."),
    ("message", "Message",
     "Short, with bullet points if you actually listed several things."),
    ("email", "Email",
     "Paragraphs where you changed topic, numbered steps where you counted "
     "them off. A greeting only if you greeted someone."),
]

POSITIONS = [
    ("bottom-center", "Bottom centre"),
    ("bottom-right", "Bottom right"),
    ("top-center", "Top centre"),
    ("center", "Middle of the screen"),
]

PAD = 14


class SettingsWindow:
    def __init__(self, on_saved=None, master=None):
        self.on_saved = on_saved
        self.cfg = load_config()
        self._vars: dict[str, tk.Variable] = {}
        self._restart_needed = False
        self._dirty = False
        # Only one Tk root can exist per process; a second one fails to start. A
        # caller may therefore pass an existing root, which is how tests drive
        # this window and the setup wizard in the same run.
        self._owns_root = master is None

        self.root = tk.Tk() if self._owns_root else tk.Toplevel(master)
        self.root.title("Casper Flow settings")
        self.root.minsize(620, 520)
        self.root.geometry("680x600")
        apply_window_icon(self.root)

        self._build()
        self.root.protocol("WM_DELETE_WINDOW", self._on_close)

    # -- helpers -------------------------------------------------------

    def _var(self, key, kind=tk.StringVar):
        """A tk variable seeded from the current config, remembered by key."""
        value = self.cfg.get(key, DEFAULTS.get(key))
        v = kind(value="" if value is None else value)
        self._vars[key] = v
        return v

    @staticmethod
    def _hint(parent, text: str, **kw):
        lbl = ttk.Label(parent, text=text, foreground="#555", wraplength=560,
                        justify="left")
        lbl.pack(anchor="w", padx=PAD, pady=(0, 8), **kw)
        return lbl

    @staticmethod
    def _heading(parent, text: str):
        ttk.Label(parent, text=text, font=("Segoe UI", 11, "bold")).pack(
            anchor="w", padx=PAD, pady=(PAD, 4))

    # -- construction --------------------------------------------------

    def _build(self):
        outer = ttk.Frame(self.root)
        outer.pack(fill="both", expand=True)

        nb = ttk.Notebook(outer)
        nb.pack(fill="both", expand=True, padx=10, pady=10)

        for name, builder in (
            ("Dictation", self._tab_dictation),
            ("Words", self._tab_words),
            ("Formatting", self._tab_formatting),
            ("Accuracy & speed", self._tab_models),
            ("Appearance", self._tab_appearance),
            ("Privacy", self._tab_privacy),
            ("Diagnostics", self._tab_diagnostics),
        ):
            frame = ttk.Frame(nb)
            nb.add(frame, text=f"  {name}  ")
            builder(frame)

        bar = ttk.Frame(outer)
        bar.pack(fill="x", padx=10, pady=(0, 10))
        ttk.Button(bar, text="Save", command=self._save).pack(side="right")
        ttk.Button(bar, text="Cancel", command=self._cancel).pack(
            side="right", padx=6)
        ttk.Button(bar, text="Open settings file",
                   command=self._open_settings_file).pack(side="left")

        self.status = ttk.Label(bar, text="", foreground="#0a7")
        self.status.pack(side="left", padx=12)

    # -- Dictation -----------------------------------------------------

    def _tab_dictation(self, f):
        self._heading(f, "Push-to-talk key")
        row = ttk.Frame(f)
        row.pack(fill="x", padx=PAD)
        current = str(self.cfg.get("hotkey", "caps lock"))
        self._var("hotkey")  # so Save writes the key even if they never recapture
        self._hotkey_label = ttk.Label(
            row, text=current.upper(),
            font=("Consolas", 12, "bold"), relief="solid", padding=(10, 5))
        self._hotkey_label.pack(side="left")
        ttk.Button(row, text="Press a key to change...",
                   command=self._capture_hotkey).pack(side="left", padx=10)
        self._hint(f, "Hold this key to dictate. A quick tap still does whatever "
                      "the key normally does, so Caps Lock keeps working as Caps "
                      "Lock.\n\nDo not pick Alt, Ctrl, Shift or the Windows key "
                      "on their own: Windows needs those for Alt+Tab, copy/paste "
                      "and the Start menu.\n\nAfter you pick a key, click Save, "
                      "then quit Casper from the tray and start it again. Closing "
                      "this window without Save discards the new key.\n\nThe Fn "
                      "key cannot be used: it is handled inside the keyboard and "
                      "never reaches Windows, so no application can see it.")

        self._heading(f, "How long to hold")
        hold = self._var("min_hold_seconds", tk.DoubleVar)
        srow = ttk.Frame(f)
        srow.pack(fill="x", padx=PAD)
        self._hold_read = ttk.Label(srow, width=10,
                                    text=f"{float(hold.get()):.1f} s")
        self._hold_read.pack(side="right")
        scale = ttk.Scale(srow, from_=0.2, to=4.0, variable=hold,
                          command=lambda _v: self._hold_read.configure(
                              text=f"{hold.get():.1f} s"))
        scale.pack(side="left", fill="x", expand=True)
        self._hint(f, "Longer means fewer dictations started by accident. Shorter "
                      "means you can dictate just a few words. Anything held for "
                      "less than this is thrown away, so if short phrases keep "
                      "vanishing, lower it.")

    def _capture_hotkey(self):
        """Listen for one real keypress and show what arrived."""
        win = tk.Toplevel(self.root)
        win.title("Press a key")
        win.geometry("380x150")
        win.transient(self.root)
        win.grab_set()
        ttk.Label(win, text="Press the key you want to hold.",
                  font=("Segoe UI", 10)).pack(pady=(24, 6))
        shown = ttk.Label(win, text="waiting...", font=("Consolas", 13, "bold"))
        shown.pack()

        state = {"name": None}

        def worker():
            try:
                import keyboard
                event = keyboard.read_event(suppress=False)
                while event.event_type != "down":
                    event = keyboard.read_event(suppress=False)
                state["name"] = event.name
            except Exception as e:
                log.debug(f"hotkey capture failed: {e}")

        def poll():
            if state["name"]:
                name = state["name"]
                shown.configure(text=name.upper())
                if name == "fn":
                    # Cannot happen in practice, which is the point worth saying.
                    messagebox.showwarning(
                        "Fn cannot be used",
                        "The Fn key is handled inside your keyboard and never "
                        "reaches Windows, so no application can detect it. "
                        "Pick another key.", parent=win)
                else:
                    from hotkey import normalise, unsafe_bare_modifier
                    name = normalise(name)
                    reason = unsafe_bare_modifier(name)
                    if reason:
                        messagebox.showwarning(
                            "That key would break Windows shortcuts",
                            reason, parent=win)
                    else:
                        self._vars["hotkey"] = tk.StringVar(value=name)
                        self._hotkey_label.configure(text=name.upper())
                        self._restart_needed = True
                        self._dirty = True
                win.after(500, win.destroy)
                return
            win.after(80, poll)

        threading.Thread(target=worker, daemon=True).start()
        poll()

    # -- Words ---------------------------------------------------------

    def _tab_words(self, f):
        self._heading(f, "Your words")
        self._hint(f, "No speech model has heard of your colleagues or your "
                      "company. Names are the weakest part of any dictation "
                      "tool, so add the ones you use.")

        ttk.Label(f, text="Names, companies, jargon - one per line:").pack(
            anchor="w", padx=PAD)
        self._vocab = tk.Text(f, height=8, wrap="none")
        self._vocab.pack(fill="both", expand=True, padx=PAD, pady=(4, 4))
        self._vocab.insert("1.0", "\n".join(self.cfg.get("vocabulary") or []))
        self._hint(f, "These fix capitalisation and spelling when the word was "
                      "heard correctly - 'whatsapp' becomes 'WhatsApp'. They "
                      "cannot rescue a word that came out as something else "
                      "entirely.")

        self._heading(f, "Fix a mistake that keeps happening")
        ttk.Label(f, text="One per line, as    heard = meant").pack(
            anchor="w", padx=PAD)
        self._fixes = tk.Text(f, height=5, wrap="none")
        self._fixes.pack(fill="x", padx=PAD, pady=(4, 4))
        self._fixes.insert("1.0", "\n".join(
            f"{k} = {v}" for k, v in (self.cfg.get("corrections") or {}).items()))
        self._hint(f, "Example:    thank you office = Bangalore office")

    # -- Formatting ----------------------------------------------------

    def _tab_formatting(self, f):
        self._heading(f, "How should the text be laid out?")
        self._hint(f, "Casper Flow does not guess this from whichever window you "
                      "are in. Guessing wrong and quietly reformatting what you "
                      "said is worse than asking once.")

        mode = self._var("format_mode")
        for value, label, detail in FORMAT_MODES:
            ttk.Radiobutton(f, text=label, value=value, variable=mode).pack(
                anchor="w", padx=PAD)
            self._hint(f, "      " + detail)

        self._heading(f, "Fix my grammar")
        grammar = self._var("grammar_fix", tk.BooleanVar)
        ttk.Checkbutton(
            f, text="Correct tense, agreement and word order",
            variable=grammar).pack(anchor="w", padx=PAD)
        self._hint(f, "A correction pass, not a rewrite: sentences that are "
                      "already correct come back untouched. It will not change "
                      "a number, a name or a date, and it will not turn a "
                      "'maybe' into a 'yes'.")

        self._heading(f, "What these need, and what they risk")
        backend = str(self.cfg.get("llm_backend", "rules")).lower()
        if backend == "rules":
            self._hint(
                f,
                "Neither option does anything yet. Both need a language model "
                "that can write, and the current cleanup setting is the "
                "built-in rules, which cannot.\n\nInstall Ollama (free, runs on "
                "this computer) and set llm_backend to \"ollama\" in "
                "settings.json. Your text still never leaves the machine.")
        else:
            self._hint(f, f"Using the {backend!r} backend for these.")

        self._hint(f, "Everything else in the cleanup step is a fixed rule and "
                      "cannot produce a word you did not say. These two can, so "
                      "the result is checked before it is pasted. If it comes "
                      "back much longer, much shorter, or missing a number you "
                      "dictated, it is thrown away and you get the plain tidy-up "
                      "instead. Your dictation is never lost.")

    # -- Accuracy & speed ----------------------------------------------

    def _tab_models(self, f):
        self._heading(f, "How you talk")
        self._hint(f, "This picks the speech model. Accuracy figures are measured "
                      "on real recordings, not estimates.")

        current = str(self.cfg.get("whisper_model", "swift-ct2"))
        self._profile = tk.StringVar(
            value=current if any(p["id"] == current for p in PROFILES) else "other")

        for p in PROFILES:
            installed = self._model_installed(p["id"])
            rb = ttk.Radiobutton(
                f, text=p["label"] + ("" if installed else "   (not installed)"),
                value=p["id"], variable=self._profile,
                state="normal" if installed else "disabled")
            rb.pack(anchor="w", padx=PAD)
            self._hint(f, "      " + p["detail"])

        if self._profile.get() == "other":
            ttk.Radiobutton(f, text=f"Keep current setting ({current})",
                            value="other", variable=self._profile).pack(
                anchor="w", padx=PAD)

        self._heading(f, "Tidy up what I said")
        polish = self._var("llm_polish", tk.BooleanVar)
        ttk.Checkbutton(f, text="Remove 'um' and 'uh', fix punctuation and capitals",
                        variable=polish).pack(anchor="w", padx=PAD)
        self._hint(f, "This is a fixed set of rules, not an AI rewrite, so it "
                      "cannot invent words you did not say.\n\nGrammar "
                      "correction and laying text out as bullets or an email "
                      "live in the Formatting tab. They are off by default, "
                      "because they can change your meaning.")

    @staticmethod
    def _model_installed(name: str) -> bool:
        try:
            import transcribe
            return transcribe.resolve_model(name) != name or name in \
                transcribe._cached_models()
        except Exception:
            return True

    # -- Appearance ----------------------------------------------------

    def _tab_appearance(self, f):
        self._heading(f, "On-screen indicator")
        style = self._var("pill_style")
        for value, label, detail in OVERLAY_STYLES:
            ttk.Radiobutton(f, text=label, value=value, variable=style).pack(
                anchor="w", padx=PAD)
            self._hint(f, "      " + detail)

        self._heading(f, "Where it appears")
        pos = self._var("pill_position")
        box = ttk.Combobox(f, values=[p[1] for p in POSITIONS], state="readonly",
                           width=28)
        box.pack(anchor="w", padx=PAD)
        current = str(pos.get())
        box.set(dict(POSITIONS).get(current, POSITIONS[0][1]))
        self._position_box = box

        self._heading(f, "Size")
        scale_var = self._var("pill_scale", tk.DoubleVar)
        row = ttk.Frame(f)
        row.pack(fill="x", padx=PAD)
        read = ttk.Label(row, width=8, text=f"{float(scale_var.get()):.1f}x")
        read.pack(side="right")
        ttk.Scale(row, from_=0.5, to=3.0, variable=scale_var,
                  command=lambda _v: read.configure(
                      text=f"{scale_var.get():.1f}x")).pack(
            side="left", fill="x", expand=True)

        ttk.Checkbutton(f, text="Show the indicator at all",
                        variable=self._var("show_pill", tk.BooleanVar)).pack(
            anchor="w", padx=PAD, pady=(10, 0))

    # -- Privacy -------------------------------------------------------

    def _tab_privacy(self, f):
        self._heading(f, "Your audio never leaves this computer")
        self._hint(f,
                   "Speech recognition runs on your own processor. There is no "
                   "account, no telemetry and no analytics, and nothing is "
                   "uploaded.\n\nThis is enforced in the code immediately before "
                   "any network call would happen, not by a setting that could be "
                   "changed by accident.")

        offline = self._var("offline_only", tk.BooleanVar)
        cb = ttk.Checkbutton(
            f, text="Refuse anything that would send audio or text away",
            variable=offline)
        cb.pack(anchor="w", padx=PAD)
        self._hint(f, "Turning this off does nothing on its own. It only allows "
                      "the cloud options, which also need an API key you supply "
                      "yourself.")

        self._heading(f, "Microphone")
        self._hint(f, f"Recordings are written to a temporary file and deleted as "
                      f"soon as the text is produced. Settings and logs live in:"
                      f"\n{DATA_DIR}")
        ttk.Button(f, text="Open that folder",
                   command=lambda: self._open_path(DATA_DIR)).pack(
            anchor="w", padx=PAD)

    # -- Diagnostics ---------------------------------------------------

    def _tab_diagnostics(self, f):
        self._heading(f, "Is everything working?")
        self._hint(f, "Runs the same checks as the command-line tool: "
                      "dependencies, settings, the hotkey, the microphone, the "
                      "clipboard and the speech model.")
        row = ttk.Frame(f)
        row.pack(fill="x", padx=PAD)
        ttk.Button(row, text="Run checks", command=self._run_doctor).pack(
            side="left")
        ttk.Button(row, text="Copy report",
                   command=self._copy_report).pack(side="left", padx=6)
        ttk.Button(row, text="Open log",
                   command=lambda: self._open_path(DATA_DIR / "casper.log")).pack(
            side="left")

        self._doctor_out = tk.Text(f, height=16, wrap="word",
                                   font=("Consolas", 9))
        self._doctor_out.pack(fill="both", expand=True, padx=PAD, pady=10)
        self._doctor_out.insert("1.0", "Press 'Run checks'.\n")

    def _run_doctor(self):
        self._doctor_out.delete("1.0", "end")
        self._doctor_out.insert("1.0", "Running...\n")

        def worker():
            import io
            import contextlib
            buf = io.StringIO()
            try:
                import doctor
                with contextlib.redirect_stdout(buf):
                    doctor.main()
            except SystemExit:
                pass
            except Exception as e:
                buf.write(f"\nThe checks themselves failed: {e}\n")
            text = buf.getvalue() or "(no output)"
            self.root.after(0, lambda: self._show_doctor(text))

        threading.Thread(target=worker, daemon=True).start()

    def _show_doctor(self, text: str):
        self._doctor_out.delete("1.0", "end")
        self._doctor_out.insert("1.0", text)

    def _copy_report(self):
        text = self._doctor_out.get("1.0", "end").strip()
        self.root.clipboard_clear()
        self.root.clipboard_append(
            "```\n" + text + "\n```\n\n"
            "Casper Flow diagnostics, pasted from the Settings window.")
        self._flash("Report copied - paste it into a GitHub issue")

    # -- saving --------------------------------------------------------

    def _collect(self) -> dict:
        out = {}
        for key, var in self._vars.items():
            try:
                value = var.get()
            except Exception:
                continue
            if key in ("min_hold_seconds", "pill_scale"):
                value = round(float(value), 2)
            if isinstance(value, str) and value == "" and DEFAULTS.get(key) is None:
                value = None
            out[key] = value

        chosen = self._profile.get()
        if chosen != "other":
            out["whisper_model"] = chosen
            for p in PROFILES:
                if p["id"] == chosen:
                    out["language"] = p["language"]

        label_to_pos = {label: value for value, label in POSITIONS}
        out["pill_position"] = label_to_pos.get(
            self._position_box.get(), "bottom-center")

        # The blob and capsule show no text, so previews would transcribe
        # repeatedly for nothing.
        out["live_preview"] = out.get("pill_style") == "caption"

        vocab = [ln.strip() for ln in
                 self._vocab.get("1.0", "end").splitlines() if ln.strip()]
        out["vocabulary"] = vocab

        fixes = {}
        for line in self._fixes.get("1.0", "end").splitlines():
            if "=" in line:
                heard, _, meant = line.partition("=")
                if heard.strip():
                    fixes[heard.strip()] = meant.strip()
        out["corrections"] = fixes
        return out

    def _save(self):
        values = self._collect()
        try:
            existing = {}
            if SETTINGS_FILE.exists():
                existing = json.loads(SETTINGS_FILE.read_text(encoding="utf-8-sig"))
            existing.update(values)
            SETTINGS_FILE.write_text(json.dumps(existing, indent=2),
                                     encoding="utf-8")
        except Exception as e:
            messagebox.showerror("Could not save",
                                 f"Writing {SETTINGS_FILE.name} failed:\n{e}",
                                 parent=self.root)
            return

        if LOCAL_SETTINGS_FILE.exists():
            overridden = sorted(
                set(json.loads(LOCAL_SETTINGS_FILE.read_text(encoding="utf-8-sig")))
                & set(values))
            if overridden:
                # Otherwise the user changes a setting, sees no effect, and has no
                # way to find out why.
                messagebox.showwarning(
                    "Some settings are overridden",
                    f"{LOCAL_SETTINGS_FILE.name} also sets: "
                    f"{', '.join(overridden)}.\n\nThose values win over what you "
                    f"just saved. Remove them from that file for these changes to "
                    f"take effect.", parent=self.root)

        if self.on_saved:
            try:
                self.on_saved()
            except Exception:
                pass

        msg = "Saved."
        if self._restart_needed:
            msg += " Restart Casper Flow for the new hotkey to take effect."
        self._dirty = False
        messagebox.showinfo("Saved", msg, parent=self.root)
        self.root.destroy()

    def _cancel(self):
        if self._dirty and not messagebox.askyesno(
                "Discard changes?",
                "The dictation key you just picked will be lost.",
                parent=self.root):
            return
        self.root.destroy()

    def _on_close(self):
        if self._dirty:
            answer = messagebox.askyesnocancel(
                "Save the new key?",
                "You picked a new dictation key. Save it before closing?\n\n"
                "After saving, quit Casper from the tray and start it again.",
                parent=self.root)
            if answer is None:
                return
            if answer:
                self._save()
                return
        self.root.destroy()

    # -- misc ----------------------------------------------------------

    def _flash(self, text: str):
        self.status.configure(text=text)
        self.root.after(4000, lambda: self.status.configure(text=""))

    def _open_settings_file(self):
        if not SETTINGS_FILE.exists():
            SETTINGS_FILE.write_text("{}", encoding="utf-8")
        self._open_path(SETTINGS_FILE)

    @staticmethod
    def _open_path(path: Path):
        try:
            import os
            os.startfile(str(path))       # noqa: S606 - Windows shell open
        except Exception:
            webbrowser.open(path.as_uri())

    def run(self):
        if self._owns_root:
            self.root.mainloop()


def open_settings(on_saved=None):
    """Open the window. Safe to call from a tray callback."""
    SettingsWindow(on_saved=on_saved).run()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    open_settings()
