/**
 * Every fact the site states about the product, in one place.
 *
 * These were placeholders until the installer existed, because there was no
 * honest value to put in them - a marketing site that invents a download size is
 * the kind of small lie that makes the large claims worthless, and this product's
 * entire pitch is "we do not send your voice anywhere", which is a claim you can
 * only ask people to take on trust.
 *
 * `version`, `installerSize` and `sha256` are measured from the artefacts that
 * `build_installer.ps1` produces. When you cut a release, these change together
 * or not at all.
 */
export const SITE = {
  /**
   * GitHub's `releases/latest/download/...` form, which always resolves to the
   * newest release. Deliberately not a versioned URL: those go stale the moment
   * a release ships, and a dead download button is the worst possible bug on a
   * page whose only job is that button.
   */
  downloadUrl:
    "https://github.com/wheretostudio/casper-flow/releases/latest/download/CasperFlowSetup.exe",
  portableUrl:
    "https://github.com/wheretostudio/casper-flow/releases/latest/download/CasperFlow-portable.zip",
  checksumsUrl:
    "https://github.com/wheretostudio/casper-flow/releases/latest/download/SHA256SUMS.txt",
  repoUrl: "https://github.com/wheretostudio/casper-flow",

  /**
   * Measured from the built CasperFlowSetup.exe, not estimated. build_installer.ps1
   * prints the size and checksum to paste in here.
   *
   * Down from 252 MB / 485 MB: PyAV was removed from the build, which was 62.6 MB
   * of bundled FFmpeg used only to decode a WAV the app had just written itself.
   */
  version: "0.1.0",
  installerSize: "234 MB",
  portableSize: "265 MB",
  installedSize: "420 MB",
  sha256: "2b0212bfb2ecf5bbcb14c78aea766bb7b05aca62f39b1544503609c69ed60d18",

  // No contactEmail. There is no support address behind this project, and the
  // legal pages no longer invite people to write to one - publishing an inbox
  // nobody watches is a worse answer than pointing at the issue tracker, which is
  // what the terms page now does.

  /** Per-user install, so no administrator rights and no UAC prompt. */
  installPath: "%LOCALAPPDATA%\\Programs\\CasperFlow",
  settingsPath: "%LOCALAPPDATA%\\Programs\\CasperFlow",

  /** Absolute origin, no trailing slash. Used for canonical URLs, og:url and the sitemap. */
  domain: "https://casperflow.app",

  license: "MIT",
  lastUpdated: "10 August 2026",

  /** Where the law that governs the terms page comes from. */
  jurisdiction: "India",
} as const;

/**
 * An absolute URL for a site-relative path. Search engines and og:url want
 * absolute; scrapers ignore relative ones outright.
 *
 * The root keeps its trailing slash so the canonical tag and public/sitemap.xml
 * agree. They disagreed at first - the tag said `https://casperflow.app` and the
 * sitemap said `https://casperflow.app/` - which is the kind of one-character
 * mismatch that has a crawler treating one page as two.
 */
export function url(path = "/"): string {
  return `${SITE.domain}${path}`;
}

/**
 * Measured accuracy, stated on the site because the alternative is letting people
 * discover it. Both numbers come from the 30-phrase Hinglish corpus recorded in
 * Phase 1 and scored by wer.py; see corpus/RESULTS.md in the repository, which is
 * generated by bench_hinglish.py and contains the full per-category table.
 *
 * These are ACCURACY figures, meaning `1 - fair word error rate`. Higher is
 * better. Saying "word error rate" next to them, which this page did, inverts
 * their meaning and turns a 91% result into a claim of 91% failure.
 *
 * **The two figures come from two different models, and each is measured on the
 * category that model is chosen for.** They are not two scores for one system, and
 * presenting them as though they were would flatter both: base.en scores 6.6% on
 * mixed speech, and the Hinglish model scores 62.4% on English. The installer asks
 * which one you want, so the honest presentation is per model.
 *
 * The Hinglish figure is 81%, and the target was 90%. It is published as it is,
 * with the gap named, because a privacy-first product that shades its own
 * measurements has nothing left to trade on.
 */
export const ACCURACY = {
  englishPercent: 91,
  englishModel: "base.en",
  englishLatencySeconds: 1.1,
  hinglishPercent: 81,
  hinglishModel: "Whisper-Hindi2Hinglish-Swift",
  hinglishLatencySeconds: 1.3,
  hinglishTarget: 90,
} as const;
